name: "MySQL CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_USER: developer
          MYSQL_DATABASE: project_db
          MYSQL_PASSWORD: ${{ secrets.DATABASEPASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOTPASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies and necessary tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          timeout=60
          counter=0
          while ! mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} -e "SELECT 1" >/dev/null 2>&1; do
            sleep 1
            counter=$((counter + 1))
            if [ $counter -gt $timeout ]; then
              echo "Timed out waiting for MySQL to start"
              exit 1
            fi
            echo "Waiting for MySQL to start..."
          done
          echo "MySQL is ready!"

      - name: Initial Schema Deployment
        run: |
          mysql -h mysql -u developer -p${{ secrets.DATABASEPASSWORD }} -e "source sql/create_database.sql;"
    
      - name: Schema Update
        run: |
          mysql -h mysql -u developer -p${{ secrets.DATABASEPASSWORD }} -e "source sql/schema_update.sql;"

      - name: Data Seeding
        run: |
          mysql -h mysql -u developer -p${{ secrets.DATABASEPASSWORD }} -e "source sql/seed_data.sql;"

      - name: Concurrent Query Execution
        run: |
          python scripts/multi_thread_queries.py

      - name: Validation Step
        run: |
          mysql -h mysql -u developer -p${{ secrets.DATABASEPASSWORD }} -e "source sql/validation.sql;"
